import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Grid } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Yomeggle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid container>
        <Grid item xs={12} md={6}>
          <div className="banner-txt">
            <div className="logo">
              <h1>Logo</h1>
            </div>
            <p>
                Omegle (oh-meg-ull) is a great way to meet new friends. When you
                use Omegle, we pick someone else at random and let you talk
                one-on-one. To help you stay safe, chats are anonymous unless
                you tell someone who you are (not suggested!), and you can stop
                a chat at any time. Predators have been known to use Omegle, so
                please be careful
              </p>
          </div>
        </Grid>
      </Grid>
    </>
  );
}
